-- AutoBot/lib/config.lua
local mq = require('mq')
local PackageMan = require('mq.PackageMan')

local lfs = PackageMan.Require('luafilesystem', 'lfs')
if not lfs then
    print('\ar[AutoBot:config] Error loading LuaFileSystem dependency\ax')
    mq.exit()
end

local M = {}

local ensured_dirs = {}

local function normalize_path(path)
  return (path or ''):gsub('/', '\\')
end

local function path_exists(path)
  path = normalize_path(path)
  local attr = lfs.attributes(path)
  return attr ~= nil
end

local function is_dir(path)
  path = normalize_path(path)
  local attr = lfs.attributes(path)
  return attr and attr.mode == 'directory'
end

local function ensure_dir(path)
  path = normalize_path(path)

  if ensured_dirs[path] then
    return true
  end

  if is_dir(path) then
    ensured_dirs[path] = true
    return true
  end

  -- recursively ensure parent first
  local parent = path:match('^(.*)\\[^\\]+$')
  if parent and parent ~= path and parent ~= '' then
    ensure_dir(parent)
  end

  local ok, err = lfs.mkdir(path)
  if not ok then
    -- mkdir can fail if another client created it between our check and mkdir call
    if not is_dir(path) then
      return false, err
    end
  end

  ensured_dirs[path] = true
  return true
end

local function serialize_value(v, indent)
  indent = indent or ''
  local t = type(v)

  if t == 'string' then
    return string.format('%q', v)
  elseif t == 'number' or t == 'boolean' then
    return tostring(v)
  elseif t == 'nil' then
    return 'nil'
  elseif t == 'table' then
    return M.serialize_lua_table(v, indent)
  else
    -- userdata/function/thread should not be persisted; stringify as fallback
    return string.format('%q', tostring(v))
  end
end

function M.serialize_lua_table(t, indent)
  indent = indent or ''
  local nextIndent = indent .. '  '
  local lines = { '{' }

  for k, v in pairs(t) do
    local key
    if type(k) == 'string' and k:match('^[%a_][%w_]*$') then
      key = k
    elseif type(k) == 'number' then
      key = '[' .. k .. ']'
    else
      key = '[' .. string.format('%q', tostring(k)) .. ']'
    end

    local val = serialize_value(v, nextIndent)
    table.insert(lines, string.format('%s%s = %s,', nextIndent, key, val))
  end

  table.insert(lines, indent .. '}')
  return table.concat(lines, '\n')
end

function M.config_dir()
  -- Be consistent with your folder casing
  local dir = normalize_path(mq.luaDir .. '\\AutoBot\\config')
  local ok, err = ensure_dir(dir)
  if not ok then
    error(string.format('[AutoBot:config] Failed to ensure config dir "%s": %s', dir, tostring(err)))
  end
  return dir
end

function M.path_for(module_id)
  return M.config_dir() .. '\\' .. module_id .. '.lua'
end

function M.load(module_id, defaults)
  local path = M.path_for(module_id)

  local ok, chunkOrErr = pcall(loadfile, path)
  if not ok or not chunkOrErr then
    return defaults or {}, path
  end

  local ok2, tbl = pcall(chunkOrErr)
  if ok2 and type(tbl) == 'table' then
    local out = {}

    -- defaults first
    for k, v in pairs(defaults or {}) do
      out[k] = v
    end

    -- loaded values override defaults
    for k, v in pairs(tbl) do
      out[k] = v
    end

    return out, path
  end

  return defaults or {}, path
end

function M.save(module_id, tbl)
  local path = M.path_for(module_id)
  local f, err = io.open(path, 'w')
  if not f then
    return false, err
  end

  f:write('-- Auto-generated by AutoBot. Safe to edit.\n')
  f:write('return ')
  f:write(M.serialize_lua_table(tbl))
  f:write('\n')
  f:close()

  return true
end

function M.clear(module_id)
  local path = M.path_for(module_id)
  os.remove(path)
end

return M